### PR TITLE
Logging tocsv

### PR DESCRIPTION
**Pull request by MaximeHollebecq**
#1 Added logger that log data into a csv saved locally 
- the path can be modified into the logtodisk GameObject
- all of the gathered data are from the avatar.cs script
- the avatar script is sending data through the notify function 
- the logtodisk script write the data when the application is closed
- an overwritting checkbox is Added to the unity UI which toggle the overwritting

### CODE REVIEW

**Comment by bastianilso** [comment]
Congrats on submitting the first pull request @MaximeHollebecq ! :+1: 

First, I am going to give you some feedback just on the commits themselves, so you get a gist idea of it. I will test the code out, once I am back in office.


General comments:
- Please start commit messages with upper-case. See [How to write a Git Commit Message](https://chris.beams.io/posts/git-commit/).

**added script for localy logging data to csv files**
- I would like you to be a bit more specific here (or literal). This file on its own, does not log data to CSV. What you are adding is a "log notifier". You will need to describe in the commit body what the purpose and intention of this class is. Why do we need it?
- Besides this issue, I am not sure `lognotifier.cs` is necessary. You seem to be making an interface for and proceed to implement the interface, but only with `Avatar.cs` - I suggest you just let Avatar.cs keep the notify function for now to simplify the implementation. :smile_cat: 

**Added files to log data in csv**
- You have some commented out code in `Logtodisk.cs` here. This should eventually be removed in the final code.

**added notification from avatar class to the logtodisk class**
- Your changes to `LogToDisk.cs` should be squashed with "Added files to log data in csv" commit.


I will give feedback on the rest of the commits later. :tiger2: To make changes to your commit, you will need to learn to do an [Interactive Git Rebase](https://www.youtube.com/watch?v=ElRzTuYln0M). Quentin and Yohann might be able to help you.

**Comment by bastianilso** [comment]
@MaximeHollebecq I tested out your branch, very cool. ⛹  I let the game run for 3 trials. In the first obstacle the kiwi passed through the obstacle. In the two others, the kiwi jumped. Now I have the following CSV file:
image

Some feedback on the behavior:
- "blinkDiscarded" should be logged as "BlinkDiscarded" so that we are consistent with how we capitalize the letters. Same with "blinkAccepted" (= "BlinkAccepted").
- I passed through an obstacle in the first trial, but there is no "KiwiObstacle" event logged in the CSV.
- I did not provide any input (fx press spacebar) during the game. Therefore there cannot have been any "BlinkAccepted" events. Those events should instead be "ShamFeedback" events.
- Since I did not provide any input, neither can there be any "BlinkDiscarded" events. "BlinkDiscarded" events should be fired when i try to provide input, but the input is ignored by the game.

If you have some questions related to these comments, let me know. 👍

**Comment by MaximeHollebecq** [comment]
@bastianilso The input bug has been solved, by re-reading the entire code , i have found that an OR is used instead of a AND operator. its now fixed and i have also performed 3 successful test in a row  wich log also properly all of the data.

**Comment by bastianilso** [comment]
@MaximeHollebecq great work 🌷 I can confirm that pressing the up arrow seems to respond much better now. We might want to verify that the behavior is correct using the actual eye tracker hardware too. I will hand you it.

We are 99% there now, but before we merge, there are a few improvements I would really like on the logging:
- Whenever a person blinks/presses up arrow outside the trampoline, send an "invalidBlink" event. For example, if the person blinks during the Dont't Blink period, if the person blinks after being lifted into the air, or blinks while in the obstacle. Basically, any time a blink happens where the blink can be considered "invalid".
- Even if my blink is discarded (the kiwi is on trampoline, but no jumping happens if i press the up arrow), I dont see any BlinkDiscarded events in the log. (?)
- I would like to have a "TrialBegin" and a "TrialFinish" event, which marks the start and end of each trial.

**Comment by MaximeHollebecq** [comment]
@bastianilso  the eye tracker is now working correctly :eyes: , after running 5 successful try , every data is recorded into the csv files using the blink of my eyes.

**Comment by MaximeHollebecq** [comment]
@bastianilso Every commits are modified and clean , i'm waiting for your review for modifications or merge.
The issue about the keyboard input without the eye tracker plugged on is also open. 
Actually what you can see from the game log on unity is through the console . 
the log on the console are about : 

- Any invalid blink will print : invalid
- While the user is blinking into the trampoline zone , the input number will be printed.
1. input 0 = BlinkDiscarded  
2. input 1 = BlinkAccepted
3. input 2 = ShamFeedback
- A warning log message will appear if the csv file is overwrited (overwriting checkbox is check)
- When the game is stopped , the path of the csv file is write on the console 

Console Log

**Review by bastianilso — APPROVED** [review]
Commits have sensible division and are clean now. Nice job! 🐊

**Pull request merged**
